---
services:
  django:
    container_name: django_basic
    build: ./django_container/
    volumes:
      - .:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  mysql:
    container_name: django_basic_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_DATABASE: django_db
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
